-- Inventory + WhatsApp order reservation system
-- Run this AFTER admin-only-rls.sql.
-- Safe to re-run if the previous inventory migration was only partially applied.

alter table public.products
  add column if not exists stock_quantity integer not null default 0;

-- Add the non-negative stock constraint only if it does not already exist.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.products'::regclass
      and conname = 'products_stock_quantity_nonnegative'
  ) then
    alter table public.products
      add constraint products_stock_quantity_nonnegative
      check (stock_quantity >= 0);
  end if;
end $$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  customer_name text,
  customer_email text,
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled')),
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  line_total numeric(12,2) not null
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Customers do not get direct INSERT/UPDATE/DELETE access to orders or order_items.
-- Orders are created through the secure create_order() RPC below.
revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;

grant select on public.orders, public.order_items to authenticated;

-- Create/replace the functions BEFORE granting/revoking function permissions.
create or replace function public.create_order(
  p_items jsonb,
  p_customer_name text default null,
  p_customer_email text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_total numeric(12,2) := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_user_id uuid := auth.uid();
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart is empty';
  end if;

  insert into public.orders(user_id, customer_name, customer_email, status, total)
  values (
    v_user_id,
    nullif(trim(p_customer_name), ''),
    nullif(trim(p_customer_email), ''),
    'pending',
    0
  )
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    begin
      v_qty := (v_item->>'quantity')::integer;
    exception when others then
      raise exception 'Invalid quantity';
    end;

    if v_qty is null or v_qty <= 0 then
      raise exception 'Invalid quantity';
    end if;

    select * into v_product
    from public.products
    where id = (v_item->>'product_id')::uuid
    for update;

    if not found then
      raise exception 'Product not found';
    end if;

    if not v_product.available or coalesce(v_product.stock_quantity, 0) < v_qty then
      raise exception 'Not enough stock for %', v_product.name;
    end if;

    update public.products
      set stock_quantity = stock_quantity - v_qty,
          available = (stock_quantity - v_qty) > 0
      where id = v_product.id;

    insert into public.order_items(
      order_id, product_id, product_name, quantity, unit_price, line_total
    )
    values (
      v_order_id,
      v_product.id,
      v_product.name,
      v_qty,
      v_product.price,
      v_product.price * v_qty
    );

    v_total := v_total + (v_product.price * v_qty);
  end loop;

  update public.orders
  set total = v_total, updated_at = now()
  where id = v_order_id;

  return v_order_id;
exception when others then
  -- Because this is one PostgreSQL transaction, any failure rolls back
  -- the order and all stock changes automatically.
  raise;
end;
$$;

create or replace function public.confirm_order(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() <> 'a7ebcd42-0d22-43cd-b8b3-06e131d7cbed'::uuid then
    raise exception 'Administrator access required';
  end if;

  update public.orders
  set status = 'confirmed', updated_at = now()
  where id = p_order_id and status = 'pending';

  if not found then
    raise exception 'Order not found or is no longer pending';
  end if;
end;
$$;

create or replace function public.cancel_order(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_order public.orders%rowtype;
begin
  if auth.uid() <> 'a7ebcd42-0d22-43cd-b8b3-06e131d7cbed'::uuid then
    raise exception 'Administrator access required';
  end if;

  select * into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'Order not found';
  end if;

  if v_order.status <> 'pending' then
    raise exception 'Only pending orders can be cancelled';
  end if;

  for v_item in
    select * from public.order_items where order_id = p_order_id
  loop
    update public.products
    set stock_quantity = stock_quantity + v_item.quantity,
        available = true
    where id = v_item.product_id;
  end loop;

  update public.orders
  set status = 'cancelled', updated_at = now()
  where id = p_order_id;
end;
$$;

-- Lock down the SECURITY DEFINER functions. By default PostgreSQL gives
-- functions EXECUTE to PUBLIC, so explicitly revoke that and grant only what is needed.
revoke all on function public.create_order(jsonb, text, text) from public, anon, authenticated;
revoke all on function public.confirm_order(uuid) from public, anon, authenticated;
revoke all on function public.cancel_order(uuid) from public, anon, authenticated;

grant execute on function public.create_order(jsonb, text, text) to anon, authenticated;
grant execute on function public.confirm_order(uuid) to authenticated;
grant execute on function public.cancel_order(uuid) to authenticated;

-- Admin can read order details; customers do not need direct table access.
drop policy if exists "Admin can read orders" on public.orders;
create policy "Admin can read orders"
on public.orders
for select to authenticated
using (auth.uid() = 'a7ebcd42-0d22-43cd-b8b3-06e131d7cbed'::uuid);

drop policy if exists "Admin can read order items" on public.order_items;
create policy "Admin can read order items"
on public.order_items
for select to authenticated
using (auth.uid() = 'a7ebcd42-0d22-43cd-b8b3-06e131d7cbed'::uuid);

-- Allow the admin to continue reading/writing products through the existing
-- admin-only RLS policies from admin-only-rls.sql.
